Create Database P1_Relail ;

---- Create Table ?

Create Table dbo.Retail_Sale
( transactions_id INT PRIMARY KEY,
  sale_date DATE,
  sale_time TIME,
  customer_id INT,
  gender VARCHAR (20),
  age INT,
 Category VARCHAR (20),
 quantiy INT,
 price_per_unit FLOAT,
 cogs FLOAT,
 total_sale FLOAT ) ;


---- import Data into Existing Table ?
Select * from dbo.Retail_Sale ;

--- Select Top 10 ?
Select TOP 10 * from dbo.Retail_Sale ;    


---- Check Table - Names - Data-Types - Col_Name ?
SELECT TABLE_NAME , COLUMN_NAME , DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS ;

 
---- Count All Record ? {Data Cleaning}
SELECT COUNT(*) FROM DBO.Retail_Sale ;

 ---- Find Null Values ?
SELECT * FROM DBO.Retail_Sale 
WHERE transactions_id IS NULL ;

SELECT * FROM DBO.Retail_Sale 
WHERE sale_date IS NULL ;

SELECT * FROM DBO.Retail_Sale 
WHERE transactions_id IS NULL 
OR sale_date IS NULL 
OR sale_time IS NULL
OR customer_id IS NULL
OR gender IS NULL 
OR Category IS NULL
OR quantiy IS NULL
OR price_per_unit IS NULL
OR cogs IS NULL  OR  total_sale IS NULL ;

---- Delete Null Values ?
DELETE FROM DBO.Retail_Sale
 WHERE transactions_id IS NULL 
OR sale_date IS NULL 
OR sale_time IS NULL
OR customer_id IS NULL
OR gender IS NULL 
OR Category IS NULL
OR quantiy IS NULL
OR price_per_unit IS NULL
OR cogs IS NULL  OR  total_sale IS NULL ;

---- {Data Exploration}

---- How many Sales we have ?
SELECT COUNT (*) AS TOTAL_SALE FROM  DBO.Retail_Sale ;

---- How many Unique Customers we Have ?
SELECT COUNT(DISTINCT customer_id) AS UNIQUE_CUST
FROM DBO.Retail_Sale ;

---- How many Unique Category we Have WITH Name ?
SELECT COUNT(DISTINCT CATEGORY) AS [UNIQUE CATEGORY]
FROM DBO.Retail_Sale ;
SELECT DISTINCT Category FROM DBO.Retail_Sale ;


---- { Data Analysis & Business key Problem }

--- Q.1 Write a SQL Query to Retrieve All Columns for Sales made on '2022-11-05' ?
SELECT * FROM DBO.Retail_Sale 
WHERE sale_date = '2022-11-05' ;

--- Q.2 Write a SQL Query to Retrieve All Transactions Where the Category is 'Clothing'
------- And the Quantity Sold is More Than 04 in the Month of Nov-2022 ?
SELECT *
	 FROM  DBO.RETAIL_SALE 
	WHERE CATEGORY = 'CLOTHING' 
	AND quantiy >= 04 
	AND FORMAT(SALE_DATE ,'yyyy-MM')='2022-11' ;

--- Q.3 Write a SQL Query to Calculate the Total Sales (total_sale) for Each Category ?
Select Category,
SUM(total_sale) as [Total Sales] from Retail_Sale
group by Category ;

--- Q.4 Write a SQL Query to find the Average Age of Customers who purchased items from the 'Beauty' category.?
Select AVG (age) as Avg_cust_age from Retail_Sale
where Category = 'Beauty' ;

--- Q.5 Write a SQL Query to find All Transactions where the Total_Sale is Greater than 1000.?
Select * from Retail_Sale Where total_sale >1000 ;

---Q.6 Write a SQL Query to find the Total Number of Transactions 
----- (transaction_id) made By Each Gender in Each Category.?
Select gender , Category ,
Count(*) as Total 
from Retail_Sale
group by Category,gender   ;

---- Q.7 Write a SQL Query to calculate the Average Sale for Each Month. 
---- Find out Best selling Month in Each Year ?

SELECT Year, Month, Avg_sales
FROM 
(
 Select 
   YEAR(sale_date) As Year ,
   MONTH(sale_date) As Month,
   AVG(total_sale) AS Avg_sales ,
   Rank() Over (Partition By YEAR(sale_date) 
   Order By avg(total_sale)Desc) as Rank 
 From Retail_Sale 
 Group By YEAR(sale_date), MONTH(sale_date) 
 ) As T1
 WHERE RANK = 1 ;


--- Q.8 Write a SQL Query to find the Top 5 Customers Based on the Highest Total Sales ?
Select Top 5 Customer_id ,SUM(total_sale) as Max_sale 
From Retail_Sale 
GROUP BY customer_id 
Order By Max_sale Desc ;

--- Q.9 Write a SQL Query to find the Number of Unique Customers Who purchased items from Each Category ?
Select Category , COUNT(Distinct Customer_id) As Unique_custid 
From Retail_Sale
Group by Category ;


-- Using CTE { Common Table Expression }
---- Q.10 Write a SQL Query to Create Each Shift and Number of Orders 
---- ( Example Morning <=12, Afternoon Between 12 & 17, Evening >17 ) ? 

WITH Hourly_Sale
 AS 
(
SELECT * , 
  CASE 
    WHEN DATEPART(HOUR , SALE_TIME) <12 THEN 'MORNING'
    WHEN DATEPART (HOUR , SALE_TIME) BETWEEN 12 AND 17 THEN 'AFTERNOON'
    ELSE 'EVENING'
  END  AS SHIFT 
FROM Retail_Sale 
) 
SELECT SHIFT , COUNT(*) AS Total_Orders 
FROM  Hourly_Sale 
GROUP BY SHIFT ;



--- Q11.Find the Top 3 Best-Selling Category based on total sales.?
SELECT TOP 3 Category ,SUM(total_sale) As Total_sale
From Retail_Sale
Group By Category
Order By Total_sale Desc ;


---- Q12. Calculate the Total Revenue generated by Each Gender ?
SELECT GENDER ,SUM(TOTAL_SALE) AS Total_Revenue 
FROM Retail_Sale
GROUP BY GENDER ;


---- Q13.Find the Customer who made the Highest Number (TOP 5 ID) of Purchases ?
SELECT TOP 5 CUSTOMER_ID , 
COUNT(transactions_id) AS TOTAL_Transactions
FROM Retail_Sale
GROUP BY customer_id 
ORDER BY TOTAL_Transactions DESC ;

--- Q14.Calculate the Average Quantity Sold Per Transaction for Each Category ?
SELECT Category ,AVG(quantiy) AS AVG_Q
FROM Retail_Sale
GROUP BY Category ;


--- Q15.Identify the HOURS of the DAY When the Most SALES OCCUR.?

SELECT MAX(transactions_id) AS MAX,
       MIN(transactions_id) AS MIN
FROM Retail_Sale ;

SELECT DISTINCT DATEPART (HOUR , SALE_TIME) 
FROM Retail_Sale ;

SELECT DATEPART(HOUR , SALE_TIME) AS HOURS ,
COUNT(*) AS TOTAL_SALE
FROM Retail_Sale
GROUP BY DATEPART (HOUR, SALE_TIME) 
ORDER BY TOTAL_SALE DESC ;


--- Q16.Find the category with the highest profit margin (total_sale - cogs).? 
SELECT Category , 
       (total_sale - cogs) AS [Highest Profit Margin ]
FROM Retail_Sale 
ORDER BY [Highest Profit Margin ] DESC  ;


--- Q17. Retrieve the Monthly & YEARLY Sales Tren ?
SELECT TOP 10  YEAR(SALE_DATE) AS YEAR,
                MONTH(sale_date) AS MONTH ,
				SUM(total_sale) AS TOTAL_SALE
FROM Retail_Sale
GROUP BY YEAR(SALE_DATE) , MONTH(sale_date)
ORDER BY total_sale DESC ;


--- Q18.Find * customers Who made at least 03 purchases in the last 6 months ?
SELECT customer_id, 
	   COUNT(transactions_id) AS Purchase_Count  
FROM Retail_Sale  
WHERE SALE_DATE >= DATEADD(MONTH, -6, '2023-12-31')---[ July-1-2023 To Dec-31-2023 ]
GROUP BY customer_id 
HAVING COUNT(transactions_id) >= 3
ORDER BY Purchase_Count DESC ;  



--- Q19.Calculate the Percentage Contribution of Each Category to the Total Sales ?
SELECT  T_01.Category,
      SUM(T_01.total_sale) AS  [CATEGORY WISE SALES],
      ROUND((SUM(T_01.total_sale)* 100.0 ) / SUM(T_02.total_sale),05)
	   AS [PERCENTAGE  CONTRIBUTION]
FROM Retail_Sale T_01
CROSS JOIN (SELECT SUM(TOTAL_SALE) AS TOTAL_SALE FROM Retail_Sale) T_02
GROUP BY T_01.Category , T_02.TOTAL_SALE
ORDER BY [PERCENTAGE  CONTRIBUTION] DESC ; 



-- Using CTE { Common Table Expression }
---- Q20.Calculate the average time gap between purchases for each customer.?

 WITH CTE AS 
 (
 SELECT Transactions_id, Customer_id, Sale_date,
   ( LEAD(sale_date) OVER ( PARTITION BY customer_id
		  ORDER BY sale_date) )
 		  AS Next_Purchase_Date ,
  DATEDIFF( DAY, sale_date,LEAD(sale_date) OVER (PARTITION BY customer_id
          ORDER BY sale_date) ) 
		  AS Time_Gap From Retail_sale 
  )
 ---SELECT * FROM CTE ;    {---RUN ONLY CTE }

  SELECT Customer_id, 
		AVG(Time_Gap) AS AVG_TIME_GAP_BY_DAY FROM CTE 
		WHERE Time_Gap IS NOT NULL 
		GROUP BY Customer_id ;


SELECT * FROM Retail_Sale ; 



